print("Bienvenido a esta calculadora")
print("------------------------------")
print()
x = int(input("Dijite el primer numero: "))
print()
y = int(input("Dijite el segundo numer: "))
print()
op = input("Dijite la operacion: ")
print()
print(f"el resultado de {x} y {y} = result")
